# 输入：各分析CSV及run_status.csv。
# 输出：使用 @oai/artifact-tool 生成并渲染检查的正式XLSX工作簿。
rm(list=ls());options(stringsAsFactors=FALSE,warn=1)
source(file.path("config","project_config.R"),encoding="UTF-8")
source(file.path("functions","io_functions.R"),encoding="UTF-8")
with_script_log("24_generate_revision_tables", {
  expected<-list(`00_project_audit`="00_project_audit/file_inventory.csv",`01_package_environment`="01_data_inventory/package_versions.csv",`02_discovery_data_qc`="02_class_imbalance/discovery_sample_qc.csv",`03_class_weighted_models`="02_class_imbalance/weighted_cv_fold_metrics.csv",`04_repeated_downsampling`="02_class_imbalance/Table_Downsampling_S100A8_1000.csv",`05_stratified_bootstrap`="02_class_imbalance/Table_Bootstrap_Results.csv",`06_balanced_cross_validation`="02_class_imbalance/balance_strategy_fold_metrics_unweighted_down.csv",`07_class_imbalance_summary`="02_class_imbalance/Table_S100A8_FeatureStability.csv",`08_external_metadata_audit`="03_clinical_validation/sample_group_mapping_all_cohorts.csv",`09_clinical_dataset_search`="01_data_inventory/downloaded_data/download_manifest.csv",`10_clinical_comparator_validation`="03_clinical_validation/Table_ClinicalValidation_long.csv",`11_diagnostic_metrics_dca`="03_clinical_validation/Table_DCA_Calibration.csv",`12_prognosis_severity_analysis`="04_prognosis_severity/Table_Prognosis_Associations.csv",`13_clinical_meta_analysis`="03_clinical_validation/clinical_effect_random_effects_meta.csv",`14_scrna_metadata_qc`="05_single_cell_pseudobulk/donor_metadata_clean.csv",`15_scrna_pseudobulk`="05_single_cell_pseudobulk/Table_Pseudobulk_FocusGenes.csv",`16_scrna_mixed_effects`="05_single_cell_pseudobulk/Table_MixedEffects_FocusGenes.csv",`17_monocyte_reclustering`="06_monocyte_state/monocyte_resolution_audit.csv",`18_monocyte_state_annotation`="06_monocyte_state/monocyte_cluster_state_annotation.csv",`19_donor_level_abundance`="06_monocyte_state/Table_DonorLevel_StateAbundance.csv",`20_donor_level_tf_activity`="05_single_cell_pseudobulk/Table_DonorLevel_TFActivity.csv",`21_non_circular_signature`="07_non_circular_signature/independent_signature_genes.csv",`22_bulk_signature_projection`="08_bulk_singlecell_integration/Table_BulkSignature_Comparisons.csv",`23_integrated_evidence_summary`="11_logs/quality_control_report.html",`24_generate_revision_tables`="10_tables/Table_ClinicalValidation.xlsx",`25_generate_manuscript_text`="12_manuscript_revision/analysis_report.docx",`26_generate_reviewer_response`="13_response_to_reviewers/response_to_reviewers_draft.docx")
  parts<-list.files(file.path("11_logs","status_parts"),pattern="\\.csv$",full.names=TRUE);st<-if(length(parts))do.call(rbind,lapply(parts,read.csv,check.names=FALSE))else data.frame()
  for(nm in names(expected))if(!nm%in%st$script)st<-rbind(st,data.frame(script=nm,status=if(file.exists(expected[[nm]]))"Success"else"Not run",start_time="",end_time="",runtime=NA,warnings="",errors="",outputs_verified=FALSE))
  st$outputs_verified<-vapply(st$script,function(nm){p<-expected[[nm]];!is.null(p)&&file.exists(p)&&file.info(p)$size>0},logical(1));st<-st[match(names(expected),st$script),]
  write_csv_utf8(st,file.path("11_logs","run_status.csv"))
  node <- "C:/Users/ZCL/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node.exe"
  assert_file(node,"bundled Node runtime");script<-file.path("scripts","build_revision_workbooks.mjs");assert_file(script)
  code<-system2(node,script,stdout=file.path("11_logs","24_workbooks_console.log"),stderr=file.path("11_logs","24_workbooks_error.log"))
  if(code!=0)stop("artifact-tool 工作簿生成失败，退出码: ",code)
  required<-c("10_tables/Table_ClassBalance_Performance.xlsx","10_tables/Table_S100A8_FeatureStability.xlsx","10_tables/sample_group_mapping_all_cohorts.xlsx","10_tables/clinical_dataset_screening.xlsx","10_tables/Table_ClinicalValidation.xlsx","10_tables/Table_Prognosis_Associations.xlsx","10_tables/Table_Biomarker_Comparison.xlsx","10_tables/Table_DonorLevel_TFActivity.xlsx","13_response_to_reviewers/reviewer_evidence_matrix.xlsx","11_logs/run_status.xlsx")
  lapply(required,assert_file,"workbook output")
})
